### ISSUE TITLE
报错，无法访问internal class

### ISSUE THREAD

**Issue by Zanbrachrissik** [akof1314/Unity-ConsoleTiny#1]
Cannot access internal class 'EditorWindowTitleAttribute' here
Cannot access internal class 'ListViewState' here
Cannot access internal class 'SplitterState' here
全部是类似的报错，请问该怎么解决？

**Comment by akof1314** [comment]
请问你是怎么操作的呢，直接下载源码工程，是否可以正常运行。你的unity版本是多少？

**Comment by Zanbrachrissik** [comment]
直接下载的源码工程运行不了。版本是2019.4.21

**Comment by akof1314** [comment]
是否按照示例工程那样，源码放在Assets外面文件夹下，然后manifest引用
